### PR TITLE
Update Python style guide

### PR DESCRIPTION
**Pull request by radeklat**
The current Python style guide in this repository is outdated. The search team in collaboration with ML and MLI (the main users of Python in Cookpad) decided to create a new one from scratch, matching the current state. The new style guide has been stable for the last couple of month and these teams consider it de facto the style guide for Python.

The new Python style guide is in a separate repository to allow and encourage fast iteration, ownership and collaboration of the teams that use it. So we believe it should stay that way. There are couple of options of what to do with the old `cookpad/styleguide` for Python. I suggest linking to the `cookpad/python-style-guide` (this PR). However note that while `cookpad/styleguide` is public, `cookpad/python-style-guide` is private. So the link would work only for Cookpad employees. If that is a problem, we can either make `cookpad/python-style-guide` public or remove the link from the old style guide.

CC: @mattjw, @ettiee, @PermanentPon

### CODE REVIEW

**Comment by radeklat** [comment]
CC @sammeadley (not sure who owns this repo but this seems appropriate)

**Review by mattjw — APPROVED** [review]
LGTM

**Comment by radeklat** [comment]
@mattjw thanks for the approval. But I can't merge this :D The merge button is missing. I suspect I don't have the rights to merge even when approved :(

**Comment by mattjw** [comment]
@radeklat ah – this is the wrong repo! Here are the global style guides (cf Cookpad JP style guides): https://github.com/cookpad/global-style-guides/

**Comment by mattjw** [comment]
Python's here: https://github.com/cookpad/global-style-guides/tree/master/python

**Pull request closed without merging**
