### PR TITLE
[Swift] Mutating and var attributes for structs are okay to use

### PR DESCRIPTION
**Pull request by twocentstudios**
The verbiage in the removed line is a bit problematic because structs themselves *are* always immutable.

Reference material: [Chris Eidhof - Structs and Mutation in Swift](http://chris.eidhof.nl/post/structs-and-mutation-in-swift/)

### CODE REVIEW

**Comment by vincentisambart** [comment]
I'm fine with removing that line, but I don't understand why you are saying that "structs themselves are always immutable".

The original sentence was probably supposing that most of the properties of a `struct` should be defined using `let`, and I agree with you that for using `var` should be totally fine.

@giginet @slightair What do you think?

**Comment by giginet** [comment]
I agree with you to remove `do not use mutating`.
Not only removing this rule but we should add these nuances.

- We should avoid using `mutating` structs as possible.
- Structs should be defined with `var`. `let` makes no sense.

**Comment by slightair** [comment]
Please remove sentence from Japanese version.

```
- **[SHOULD]** `mutating`な構造体は利用を避けること
	    - 一般的に構造体は不変であることが期待されるため
```

https://github.com/cookpad/styleguide/blame/master/swift.ja.md#L71-L72

**Comment by twocentstudios** [comment]
@vincentisambart I should have gone into more detail with that statement. Defining a struct's attributes as `var` or their functions as `mutating` is (in my interpretation) syntactic sugar for using a standard initializer with zero or more values changed.

I'll run through some examples below. Please let me know if you think my understanding is flawed.

```swift
// From CoreGraphics
struct CGPoint {
    var x: CGFloat
    var y: CGFloat
    init(x: CGFloat, y: CGFloat)
}

// Example 1
let point1a = CGPoint(x: 0, y: 0)
let point1b = CGPoint(x: 1, y: 0)
```

When I said "structs themselves are always immutable" the struct I was referring to is `CGPoint(x: 0, y: 0)` *not* `point1a`. In Example 1 it's obvious there are two distinct `CGPoint`s and we can refer to each of them later via `point1a` and `point1b`.

Next example:

```swift
// Example 2
var point2 = CGPoint(x: 0, y: 0)
point2 = CGPoint(x: 1, y: 0)
```

In the above, `CGPoint(x: 0, y: 0)` is not changing. The external "reference" `point2` is changing (I don't know what the actual term is for "reference" because it's not a reference in the ARC sense, is it?).

Conceptually, the same thing is happening in example 3 as in example 2:

```swift
// Example 3
var point3 = CGPoint(x: 0, y: 0)
point3.x = 1
```

`CGPoint(x: 0, y: 0)` is being cast aside and now `point3` refers to a newly created `CGPoint(x: 1, y: 0)`.

Qualifying `x` as a `var` within `CGPoint` allows us to say "give me a new point with a different value of `x` but keep all the other values the same".

The difficult part is that there is 1. what *looks* like is happening, 2. what is *conceptually* happening, 3. what Swift is doing *under the hood*.

```swift
// Example 4
let point4a = CGPoint(x: 0, y: 0)
let point4b = point4a
```

In example 4, if you don't know that structs are value types it *looks* like `point4b` is an alias to `point4a`. *Conceptually*, they each have a completely separate copy of `CGPoint(x: 0, y: 0)`. And at this point *under the hood*, they actually may refer to the same underlying memory.

```swift
// Example 5
let point5a = CGPoint(x: 0, y: 0)
var point5b = point4a
point5b.x = 1
```

In example 5, if you don't know that structs are value types, it *looks* like `point5a` and `point5b` will both eventually evaluate to `CGPoint(x: 1, y: 0)`. *Conceptually*, there have been 3 distinct structs that have been created `CGPoint(x: 0, y: 0)`, `CGPoint(x: 0, y: 0)`, `CGPoint(x: 1, y: 0)` and the middle value no longer exists. *Under the hood* Swift probably only created `CGPoint(x: 1, x: 0)` when it executed the line `point5b.x = 1`. There are so many various compiler optimizations that happen depending on all kinds of context that I'll simply say "the complier will guarantee the *conceptual* behavior while doing its best to make things speedy and efficient".

**Pull request merged**
